### ISSUE TITLE
[DatabaseServiceImpl] About database source

### ISSUE THREAD

**Issue by wLUOw** [hezean/sustc#10]
### Describe your question

Should we open and close our database source in every method we implemented? Or the test will open database source at the beginning and closed at last. In class DatabaseServiceImpl method sum(int a, int b), the source is opened and doesn't close, is it a bug or the testbench will automatically close all source at last.

**Comment by hezean** [comment]
The datasource is always there, it's lifecycle is (almost) the same as the application, and will be managed by our framework.

However, the datasource holds several connections that do need to be closed after you use it.

https://github.com/hezean/sustc/blob/374686e07cc9f77d89311bea8c8eb39e9e96422b/sustc-api/src/main/java/io/sustc/service/impl/DatabaseServiceImpl.java#L77-L82

the try-with-resource state is equivalent to:

```java
Connection conn = null;
PreparedStatement stmt = null;

try {
    conn = dataSource.getConnection();
    stmt = conn.prepareStatement(sql);
    stmt.executeUpdate();
} catch (SQLException e) {
    throw new RuntimeException(e);
} finally {
    try {
        if (stmt != null) {
            stmt.close();
        }
        if (conn != null) {
            conn.close();
        }
    } catch (SQLException e) {
        throw new RuntimeException(e);
    }
}
```

is the explanation clear enough?

**Comment by hezean** [comment]
The datasource is always there, it's lifecycle is (almost) the same as the application, and will be managed by our framework.

However, the datasource holds several connections that do need to be closed after you use it.

https://github.com/hezean/sustc/blob/374686e07cc9f77d89311bea8c8eb39e9e96422b/sustc-api/src/main/java/io/sustc/service/impl/DatabaseServiceImpl.java#L77-L82

the try-with-resource state is equivalent to:

```java
Connection conn = null;
PreparedStatement stmt = null;

try {
    conn = dataSource.getConnection();
    stmt = conn.prepareStatement(sql);
    stmt.executeUpdate();
} catch (SQLException e) {
    throw new RuntimeException(e);
} finally {
    try {
        if (stmt != null) {
            stmt.close();
        }
        if (conn != null) {
            conn.close();
        }
    } catch (SQLException e) {
        throw new RuntimeException(e);
    }
}
```

is the explanation clear enough?

**Comment by wLUOw** [comment]
Thanks a lot for answering. But there is still a little issue. The DataSource object has @Autowired annotate so we can use it directly, but Connection and Statement object will be created and closed seperately in every method. Is it right?

**Comment by hezean** [comment]
That's basically correct. When you DataSource#getConnection() it just returns an idle connection from the pool, instead of creating one.
