### ISSUE TITLE
[Benchmark] Invalid Register User

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#106]
### Related module

Benchmark

### What happened

Wrong answer for RegisterUserReq(password=a5c221f6de374296, qq=146962499598741900, wechat=68290532#bfb5#, name=aaaa0b140, sex=MALE, birthday=2月6日, sign=dc67a346-879a-46): expected >= 0, got -1

### What you expected to happen

I believe this request is illegal because the QQ number is obviously too long. Anyone would consider this data as an abnormal input in reality. I couldn't find any description of this field in the documentation, and I need a reasonable explanation.

**Comment by ywyz233** [comment]
I think there is no specific limitation on QQ or Wechat.

**Comment by Cerulime** [comment]
> I think there is no specific limitation on QQ or Wechat.

According to the common sense of life, the content that is unclear should be judged in the most reasonable way, rather than going to the coffee shop to order 10000 Fried Rice.

**Comment by ywyz233** [comment]
> > I think there is no specific limitation on QQ or Wechat.
> 
> According to the common sense of life, the content that is unclear should be judged in the most reasonable way, rather than going to the coffee shop to order 10000 Fried Rice.

I agree what you said. I am also confused when I start doing my project. However I find it is difficult to comform all the restrictions to the fields(e.g. We do not know how bv is generated or how mid was generated or is there any restrictions on bv or mid). So I think what we need to do is to ignore these limitations.

**Comment by Cerulime** [comment]
> > > I think there is no specific limitation on QQ or Wechat.
> > 
> > 
> > According to the common sense of life, the content that is unclear should be judged in the most reasonable way, rather than going to the coffee shop to order 10000 Fried Rice.
> 
> I agree what you said. I am also confused when I start doing my project. However I find it is difficult to comform all the restrictions to the fields(e.g. We do not know how bv is generated or how mid was generated or is there any restrictions on bv or mid). So I think what we need to do is to ignore these limitations.

There are numerous reasonable methods, including but not limited to any viable explanation. For fields like "bv" or "mid" where the algorithms are not publicly disclosed, you may adopt your own approach and explain it in your report. However, for fields such as QQ or Wechat, there are more explicit constraints, such as length or format, rather than entertaining the notion of compromise. For instance, it would be preposterous to allow a 1GB numerical string and consider it a valid QQ number.

**Comment by Cerulime** [comment]
@sses7757 @hezean I need a response.

**Comment by matthew-leng** [comment]
All data are fictional, no special limit regarding this field is mentioned in the project guidelines. Feel free to modify your implementation.

**Comment by Cerulime** [comment]
> All data are fictional, no special limit regarding this field is mentioned in the project guidelines. Feel free to modify your implementation.

6
