### ISSUE TITLE
generalRecommendations测试数据答案疑似有误

### ISSUE THREAD

**Issue by xyluoxy** [hezean/sustc#109]
### Describe your question

文档中说是："like": the rate of WATCHED users who ALSO liked this video.
"coin": the rate of WATCHED users who ALSO donated coin to this video.
"fav": the rate of WATCHED users who ALSO collected this video.

但实际上测试数据的答案是："like": the rate of WATCHED users AND liked users.
"coin": the rate of WATCHED users who AND donated coined users.
"fav": the rate of WATCHED users who AND collected users.

**Comment by WhatWEat** [comment]
是的，请按照后者，只是单纯算一个rate
