### ISSUE TITLE
命令行输入生日读取到的不是相同内容

### ISSUE THREAD

**Issue by Mandyyymeng** [hezean/sustc#110]
### Related module

Code in sustc-api

### What happened

register user里这个输出是false，命令行输入是--birthday 9月19日，然后regex不匹配

String bir=req.getBirthday();
System.out.println(bir+" "+bir.equals("9月19日"));

**Comment by Mandyyymeng** [comment]
还有是userimpl过了benchmark才会跑danmu吗，没检测到弹幕benchmark就停止了

**Comment by sses7757** [comment]
@Mandyyymeng 
1. 我控制台打印了一下，没有复现你的这个bug，这有可能是框架的问题，你可以先同步一下main分支，还不行可以尝试看看不同的JDK版本、不同的电脑能不能稳定触发这个问题
2. 你可以看看`sustc-runner\src\main\java\io\sustc\benchmark\BenchmarkService.java`，里面有具体的测试顺序，我看了一下整体顺序是video->danmu->user。

**Comment by Mandyyymeng** [comment]
同步了，我用的JDK20，请问你的是什么版本JDK？我用原来的benchmark没有问题下载新版本才有问题的

**Comment by Mandyyymeng** [comment]
> @Mandyyymeng
> 
> 1. 我控制台打印了一下，没有复现你的这个bug，这有可能是框架的问题，你可以先同步一下main分支，还不行可以尝试看看不同的JDK版本、不同的电脑能不能稳定触发这个问题
> 2. 你可以看看`sustc-runner\src\main\java\io\sustc\benchmark\BenchmarkService.java`，里面有具体的测试顺序，我看了一下整体顺序是video->danmu->user。

同步了，我用的JDK20，请问你的是什么版本JDK？我用原来的benchmark没有问题下载新版本才有问题的
