### ISSUE TITLE
[benchmark] logger not showing all elements in the args array

### ISSUE THREAD

**Issue by magicoyong** [hezean/sustc#116]
### Related module

Code in sustc-api

### What happened

why there is nothing about video ,but it can still posted

**Comment by magicoyong** [comment]
<img width="900" alt="截屏2024-01-03 00 32 27" src="https://github.com/hezean/sustc/assets/134081876/17edb4b2-4d15-43f2-adf6-0995d6ce7ca7">

**Comment by hezean** [comment]
just cuz the logger has some problem displaying the Object[] args, you may fix it by explicitly print the elements in the array

we would not modify the framework cuz this doesn't affect the outcome, but if you'd like to contribute a fix of it, pr welcome, otherwise feel free to close this issue
