### ISSUE TITLE
OJ提交报错FileNotFoundException

### ISSUE THREAD

**Issue by hatfail** [hezean/sustc#118]
### Related module

Benchmark

### What happened

如题，OJ提交的报错
java.io.FileNotFoundException: benchmark-1704285160966/work/sustc/run/application.properties (No such file or directory)

**Comment by hezean** [comment]
因为你build炸了，不要改api，详情看build-stderr.log

**Comment by hatfail** [comment]
build的报错是这样子，请问问题出在哪里
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:48: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.postVideo(auth, req);
                                     ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:66: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.deleteVideo(auth, bv);
                                       ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:94: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.updateVideoInfo(auth, bv, req);
                                           ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:114: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.searchVideo(auth, keywords, pageSize, pageNum);
                                       ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:119: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.getAverageViewRate(bv);
                                              ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:124: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.getHotspot(bv);
                                      ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:142: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.reviewVideo(auth, bv);
                                       ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:160: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.coinVideo(auth, bv);
                                     ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:178: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.likeVideo(auth, bv);
                                     ^
/app/benchmark-1704285160966/work/sustc/sustc-runner/src/main/java/io/sustc/command/VideoCommand.java:196: error: unreported exception SQLException; must be caught or declared to be thrown
        return videoService.collectVideo(auth, bv);
                                        ^

**Comment by hezean** [comment]
<img width="881" alt="Screenshot 2024-01-03 at 22 36 07" src="https://github.com/hezean/sustc/assets/49837965/bcbec3f5-3834-46dc-9922-534d0766e5ba">
