### ISSUE TITLE
Some questions about [deleteAccount] and [deleteVideo].

### ISSUE THREAD

**Issue by Nyanpassing** [hezean/sustc#12]
### Describe your question

If an user was deleted, should the things related to this user be deleted?
(These things may include: posted videos, reviewed videos, given likes, given coins, view history, collect information, sent danmu, followed by others, etc.)
If a video was deleted, should the things related to this video be deleted?
(These things may include: likes, collects, coins, view history, danmus, etc.)

**Comment by hezean** [comment]
certainly

we may release some test cases and sample data soon to help you confirm these

**Comment by Nyanpassing** [comment]
Thank you վ'ᴗ' ի
