### ISSUE TITLE
[BenchmarkService] some fields in videoRecords is zero

### ISSUE THREAD

**Issue by FrostyHec** [hezean/sustc#13]
### Related module

Benchmark

### What happened

When testing my code, I found out that certain fields that were supposed to have values turned out to be null.Thus, I add a log in the benchmarkService, and someaFields in video records is null, I wonder if I made some mistake or there's actually a bug. Thanks
<img width="782" alt="Snipaste_2023-12-08_01-24-47" src="https://github.com/hezean/sustc/assets/112929809/3952dd36-e8c1-4c7a-9d7e-93f4718ec326">

**Comment by hezean** [comment]
We will release an update for benchmark service, which is still wip. You may check the branch https://github.com/hezean/sustc/tree/benchmark
