### ISSUE TITLE
About the table design

### ISSUE THREAD

**Issue by Wellshh** [hezean/sustc#14]
### Describe your question

Must we design the table according to the test cased? For example, can we separate into smaller tables for design purpose?

**Comment by hezean** [comment]
You **should** split the import records to several tables to meet the normal forms. Failure to do so may lead to a deduction.

Refer to the description in project 1 (CS307):
<img width="811" alt="image" src="https://github.com/hezean/sustc/assets/49837965/6321475a-711e-4465-af6f-1d74704d7c61">
