### ISSUE TITLE
[UserService] The data for test is invalid against the request of register

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#15]
### Describe your question

In register, we need a valid birthday (not null nor empty). But the data in [users.csv](https://github.com/hezean/sustc/blob/main/sustc-runner/data/import/users.csv) doesn't have the birthday.
And another question about the UserRecord is that the type of gender should be same as RegisterUserReq.

It's important to tell us the detail of input data constraints. Such as "男" or "Male", and the data format of the birthday.

**Comment by hezean** [comment]
Regarding the data, please refer to #13.
For the data type mismatch, see #8.

**Comment by hezean** [comment]
You may update your benchmark service to the one in the `benchmark` branch to check the data value in `.ser` files, download from http://172.18.34.154/

**Comment by Cerulime** [comment]
Thanks for the data. But I still want to know if there is a **from** to **clearly specify** the format of all **input data**. I hope we can get small size data to debug, too. The test data can be like the OnlineJudge's sample data.

**Comment by sses7757** [comment]
@Cerulime We may consider smaller data, however, you may not be able to test your implementation speed with such small dataset. The data in the link is already a sampled one.

> You may update your benchmark service to the one in the `benchmark` branch to check the data value in `.ser` files, download from http://172.18.34.154/

**Comment by Cerulime** [comment]
> @Cerulime We may consider smaller data, however, you may not be able to test your implementation speed with such small dataset. The data in the link is already a sampled one.
> 
> > You may update your benchmark service to the one in the `benchmark` branch to check the data value in `.ser` files, download from http://172.18.34.154/

Thanks for your reply. I think the smaller data can help us to understand the procedure of whole project. We can also use it to check the correctness of the implementation.

**Comment by hezean** [comment]
dataset updated
