### ISSUE TITLE
Some questions about the runner's data and the field mid

### ISSUE THREAD

**Issue by Escapist2022** [hezean/sustc#16]
### Describe your question

1. I would like to use foreign keys to link my tables, but the data provided in the runner obviously violated the constraints, e.g., a user would follow another user whose mid is not in the userrecord. Is there some new data available now?
2. The method register requires us to return a new users mid, but where is the mid from, do we need to find a way to generate the mid ourselves? And what is the length of the mid? It seems that the longest uid in Bilibili has 10bits (maybe I'm wrong
Expecting for your answer~

**Comment by hezean** [comment]
### 1

it's guaranteed that

https://github.com/hezean/sustc/blob/374686e07cc9f77d89311bea8c8eb39e9e96422b/sustc-api/src/main/java/io/sustc/service/DatabaseService.java#L20

for more info, refer to https://github.com/hezean/sustc/issues/13#issuecomment-1845896714

### 2

just generate a non-negative id which is globally unique
