### ISSUE TITLE
Visibility issue in getUserInfo

### ISSUE THREAD

**Issue by fz-zsl** [hezean/sustc#17]
### Describe your question

In method `getUserInfo`, which kind of result shall we return (take videos that a user has watched for example):

- All videos that the user has watched (including deleted videos, videos not reviewed yet and videos not published yet).
- All videos in the database that the user has watched (including videos not reviewed yet and videos not published yet).
- All videos that the user has watched and can be searched by regular users.

Since the authentication information is not provided, we can't return different results base on different identities.

**Comment by WhatWEat** [comment]
just all videos in the database that the user has watched

**Comment by fz-zsl** [comment]
Thank you for your answering.
