### ISSUE TITLE
[Danmu Record] About clean the "dirty words"

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#18]
### Describe your question

In [Danmu Record](https://github.com/hezean/sustc/blob/main/sustc-api/src/main/java/io/sustc/dto/DanmuRecord.java), we need to filter danmu content when importing. Is there a sensitive word dataset for us? Or what standard should we follow to do filtering?

**Comment by sses7757** [comment]
@Cerulime This is a mistake and is corrected in the [`benchmark`](https://github.com/hezean/sustc/blob/benchmark/sustc-api/src/main/java/io/sustc/dto/DanmuRecord.java#L31) branch.
