### ISSUE TITLE
i wonder how to calculate the coins in class [UserInfoResp] 

### ISSUE THREAD

**Issue by redhecker** [hezean/sustc#21]
### Describe your question

notice that in the class [UserInfoResp], the number of coins a user owns is needed. but we didn't know the number of coins a user owns when it is registered or imported. If we just simply give it a number of 0, then nobody can give coin to a video. It's strange.
**So, please give a particular method for us to calculate the coins.**

btw, there are other fields such as level whose calculate method is not declared clearly. it is hard for us to decide how to implement the interfaces.

**Comment by hezean** [comment]
https://github.com/hezean/sustc/blob/3281c0849a841510f6ea55c66fd4177fb7af60bf/sustc-api/src/main/java/io/sustc/dto/UserRecord.java#L34-L42

for the imported users, their hold numbers of coin that are greater or equal to 0, and their level varies in [1, 6], but for the newly registered users, their initial #coin is 0, initial level is 1, just the same as the mechanism of bilibili.

you are not required to design ways for users to 'earn' coins or 'level up', and there's no such thing as 'calculating' them.

**Comment by hezean** [comment]
@redhecker 
sorry about the mistake of default level, per the existing data, the range of level is [0, 6] and the initial level should be 0.

**Comment by redhecker** [comment]
okay， thanks
