### ISSUE TITLE
Definition of invalid state in VideoService.searchVideo

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#23]
### Describe your question

In this [commit](https://github.com/hezean/sustc/commit/2fae0becc921e5d0d8c2be79cc4039b0cef510d5#diff-2d2a1abf342d0f5c61c3eee2c29108bdb9dcdadc298c3110fe9f8642f11ccb16L123), the "invisible" line was deleted. But I think it should be invalid because we can't search private videos in real life. I need a clearer response.

**Comment by sses7757** [comment]
@Cerulime It is deleted since corner cases have special returns. Besides, since you are not visible to private videos, they shall be simply absent in your returned list, which is not a corner case.

**Comment by Cerulime** [comment]
> @Cerulime It is deleted since corner cases have special returns. Besides, since you are not visible to private videos, they shall be simply absent in your returned list, which is not a corner case.

Thanks for your reply.
