### ISSUE TITLE
[Benchmark] Resource Limitation

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#24]
### Describe your question

I need to know the resource limitations for my program and the database during benchmarking, including but not limited to the program's runtime memory, database disk storage space, database user permissions, and related database configurations. This information will assist me in debugging the program and setting parameters.

**Comment by hezean** [comment]
jvm max heap size: 4g (we will use zgc)

db storage limit: 10g

user perm: `ALTER DATABASE <test_db> OWNER TO <newly_generated_regular_user>`

default config for db (postgres 16.1) and connection pool (hikaricp 4.0) will be applied

**Comment by Cerulime** [comment]
> ALTER DATABASE <test_db> OWNER TO <newly_generated_regular_user>

Sorry, I am afraid I still need to know the **shared_buffers** and **max_connections** .
