### ISSUE TITLE
Contradiction between issue #17 and issue #23

### ISSUE THREAD

**Issue by fz-zsl** [hezean/sustc#25]
### Describe your question

Issue #17 tells that we should return all the videos in the database, however, #23 tells that we should only return published videos. Which result shall we return?

**Comment by sses7757** [comment]
@fz-zsl 
There is no contradiction since a super user can see private videos (videos waiting for review) while normal users cannot. #23 is the case of a normal user.
To make things clear, I have edited the reply in #23.
