### ISSUE TITLE
[UserService] Confusion about AuthInfo

### ISSUE THREAD

**Issue by Cypher-Bruce** [hezean/sustc#26]
### Describe your question

I have confusion about the validation of `AuthInfo`.
```
     *   <li>the {@code auth} is invalid
     *     <ul>
     *       <li>both {@code qq} and {@code wechat} are non-empty while they do not correspond to same user</li>
     *       <li>{@code mid} is invalid while {@code qq} and {@code wechat} are both invalid (empty or not found)</li>
     *     </ul>
     *   </li>
```

In my understanding, there are four ways of validation:
- Validate by `mid` and `password`
- Validate by `qq`
- Validate by `wechat`
- Validate by `qq` and `wechat`

My questions are:
- Will `mid` be provided in the latter 3 validations?
- Could there be a composite validation with `password` and `qq`/`wechat`? (For example: An `AuthInfo` with `mid`, `password` and `qq` provided)

**Comment by sses7757** [comment]
@Cypher-Bruce 
1. We may or may not provide in different test cases.
2. No.

**Comment by hezean** [comment]
> Validate by `qq` and `wechat`

there won't be such case as it's not how OIDC works

**Comment by Cypher-Bruce** [comment]
Just to comfirm: When multiple unique attributes are provided(`mid`, `qq` or `wechat`), `AuthInfo` will be regarded as valid only if all attributes are valid(can found a user) and correspond to the same user.

**Comment by sses7757** [comment]
@Cypher-Bruce 
Yes.

**Comment by Cypher-Bruce** [comment]
Thank you for your reply.
