### ISSUE TITLE
a question about coin

### ISSUE THREAD

**Issue by redhecker** [hezean/sustc#27]
### Describe your question

when a user gives a coin to a video, will his coin number change? What is the case when importing?

**Comment by sses7757** [comment]
@redhecker 
Of course his/her coin number will be decreased by 1 if he/she has remaining coins. Similarly, when he/she withdraws a coin, his/her coin number will be increased by 1.
When importing, simply set the coin numbers to the given values.

**Comment by Cerulime** [comment]
> @redhecker Of course his/her coin number will be decreased by 1 if he/she has remaining coins. Similarly, when he/she withdraws a coin, his/her coin number will be increased by 1. When importing, simply set the coin numbers to the given values.

In the doc, I didn't see any words about "withdraw a coin". Is there any update about the doc?

**Comment by redhecker** [comment]
> @redhecker Of course his/her coin number will be decreased by 1 if he/she has remaining coins. Similarly, when he/she withdraws a coin, his/her coin number will be increased by 1. When importing, simply set the coin numbers to the given values.

then what about the author of the video? that is, if A gives a coin to B's video, then will the number of B's coins increase?

**Comment by dequeueing** [comment]
> > @redhecker Of course his/her coin number will be decreased by 1 if he/she has remaining coins. Similarly, when he/she withdraws a coin, his/her coin number will be increased by 1. When importing, simply set the coin numbers to the given values.
> 
> In the doc, I didn't see any words about "withdraw a coin". Is there any update about the doc?

I agree. In the description of  method ```coinVideo``` in interface VideoService, ```the user has no coin or has donated a coin to this video``` is one of the corner cases that false shall be returned. Awaiting for for further reply...
![image](https://github.com/hezean/sustc/assets/127177415/efc5b642-8d65-4afb-90ce-81c04a92dda4)

**Comment by sses7757** [comment]
@redhecker Sorry about the mistake, the users cannot withdraw coin donations. Further documentation is updated in the latest commit.
