### ISSUE TITLE
[io.sustc.service.RecommenderService#generalRecommendations(int, int)] Counting of the rates of like/coin/favorite

### ISSUE THREAD

**Issue by Jaredanwolfgang** [hezean/sustc#28]
### Describe your question

In the RecommenderSerivice, we are asked to implement a method `generalRecommendations(int, int)`. The implNote stated that `Though users can like/coin/favorite a video without watching it, the rates of these values should be clamped to 1.` What does it mean by clamping the rates of the values to 1? 

- Does that mean if there are users who like/coin/favorite a video without watching it, then the like/coin/favorite rates for the video should be set to 1? 
- Or does that mean we need to count all the like/coin/favorite without caring whether the users watch the video?  Will the benchmark given produce results larger than 100%? 

Thank you for your prompt responding!

**Comment by sses7757** [comment]
@Jaredanwolfgang 
Just count all users who like/coin/favorite a video with/without watching it combined. This value may exceed the number of users who watched this video. In this case, the like/coin/favorite rates shall be at most 1.

**Comment by Jaredanwolfgang** [comment]
Ok! Thank you for answering
