### ISSUE TITLE
[VideoService] Character Set in tilte, owner name and description

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#29]
### Describe your question

I would like to know if the dataset only contains a specific character set(such as English).

**Comment by WhatWEat** [comment]
#33 
For example, within the given data of userRecord, you will find there are Chinese, English, and other types of data.

**Comment by Cerulime** [comment]
> #33 For example, within the given data of userRecord, you will find there are Chinese, English, and other types of data.

Thanks for your reply.
