### ISSUE TITLE
[VideoService] A question about viewTime

### ISSUE THREAD

**Issue by dequeueing** [hezean/sustc#30]
### Describe your question

Hello reviewer. My question is, if a user watches a video multiple times, what shoulded be recorded in ```viewTime```? Multiple records with view time for each watching, or the ```viewTime``` of user's latest watching? 

Thank you.

**Comment by WhatWEat** [comment]
latest watching

**Comment by sses7757** [comment]
Besides, for simplicity, there is no API to watch a video.
