### ISSUE TITLE
[Invalid import data] Too long sign

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#33]
### Related module

Benchmark

### What happened

In the small-data, it exists a invalid data.

>   WARN 11572 --- [           main] i.s.service.impl.DatabaseServiceImpl     : User mid: 1574680
> ERROR 11572 --- [           main] i.s.service.impl.DatabaseServiceImpl     : Sign is too long: ♡。                 ...                                                           一个人，走两个人的路。

### What you expected to happen

In Bilibili, the limitation of personal sign is **70** characters, as of my posting time. But in this data, the length is **92**.

### How to reproduce

If you consider it as a normal data, I think you should **provide** _us_ A DETAILED DOCUMENT ABOUT EACH DATA.

### Anything else

I have mentioned it before.

Thanks.

**Comment by sses7757** [comment]
@Cerulime You SHALL have learned about the characteristics of the provided data in PROJECT 1 when you import them.

**Comment by Cerulime** [comment]
> @Cerulime You SHALL have learned about the characteristics of the provided data in PROJECT 1 when you import them.

Sorry, I am learning the CS213. Please tell me what the PROJECT 1 said.

**Comment by hezean** [comment]
[CS307-2023Fall-Project1.pdf](https://github.com/hezean/sustc/files/13692035/CS307-2023Fall-Project1.pdf)

**Comment by Cerulime** [comment]
> [CS307-2023Fall-Project1.pdf](https://github.com/hezean/sustc/files/13692035/CS307-2023Fall-Project1.pdf)

@hezean I can't find any length limitation about the "name" or "sign" or "title" or "description". Please give a clear reply.

**Comment by Cerulime** [comment]
@sses7757 @WhatWEat What are the length limitation?
