### ISSUE TITLE
[dbimport] operating benchmark throw errors

### ISSUE THREAD

**Issue by ElyAi** [hezean/sustc#35]
### Related module

Benchmark

### What happened

![QQ图片20231216162132](https://github.com/hezean/sustc/assets/132359145/7a7e6b0a-ab34-4d31-90e6-d638ab1e6d34)
Detailed information is in the following document.
[text.txt](https://github.com/hezean/sustc/files/13691853/text.txt)

### Anything else

It works fine on the computers of other members of the team.

**Comment by XiaoMingZHM** [comment]
We can't reproduce the error.  Did you change the fields in UserRecord? Can you provide the code for UserRecord? Will this error still occur when using small data?

**Comment by ElyAi** [comment]
[UserRecord.txt](https://github.com/hezean/sustc/files/13692425/UserRecord.txt)
This is my userrecord, and small data is what I use to test.

**Comment by XiaoMingZHM** [comment]
The comment in UserRecord shows that the version of codes you are using is behind the main branch. The released datas are for newest code. You may directly merge the main into your branch. If problem still exist, you may contact me in private to check your whole code.

**Comment by XiaoMingZHM** [comment]
This bug is due to the incomplete import data. Please make sure to verify the file size after decompressing.
