### ISSUE TITLE
file not found when import

### ISSUE THREAD

**Issue by lxy-quantum** [hezean/sustc#38]
### Related module

Code in sustc-api

### What happened

![danmu](https://github.com/hezean/sustc/assets/60066705/1da403be-0fbb-461d-b85f-587f57642858)

**Comment by Cerulime** [comment]
FileNotFoundException->找不到文件
建议删去该issue，因为不具有普遍性

**Comment by lxy-quantum** [comment]
文件已经正常导入到文件夹了，为什么还会有FileNotFoundException

**Comment by lxy-quantum** [comment]
![data](https://github.com/hezean/sustc/assets/60066705/a1cf1dbd-fa80-4d82-b316-562f3647983d)
data/ 内已正常导入文件

**Comment by Franky3022** [comment]
请问解决了吗，我也遇到相同问题
