### ISSUE TITLE
Question about searching the video

### ISSUE THREAD

**Issue by redhecker** [hezean/sustc#40]
i wonder if a user can search a video which is published and reviewed and updated but not re-reviewed.
a natural idea is that the previous version can be searched while the updated version cannot, but this would lead to a great amount of work(Maybe)

**Comment by WhatWEat** [comment]
The approach we have adopted is the simplest one: videos that have been updated but not reviewed will not be viewable.

**Comment by redhecker** [comment]
okay, thanks
