### ISSUE TITLE
[Testing error] dataSource() is null when testing

### ISSUE THREAD

**Issue by dequeueing** [hezean/sustc#43]
### Describe your question

https://github.com/hezean/sustc/issues/32#issuecomment-1859022354
Hello review, I was trying to test the implementation as told in the upper issue. The error is ```this.dataSource() is null```, more detailed error in the image below.

![image](https://github.com/hezean/sustc/assets/127177415/b9f54a60-654b-4333-ae56-70a77389873a)

I have already added```@Autowired```mark before the dataSource. Since I use _helper class_ to execute certain sql commands, datasource is instantiated in the helper class.  I have also added ```@Component``` annotation before the class (otherwise ```@Autowired``` does not work).

![image](https://github.com/hezean/sustc/assets/127177415/46a23291-b76a-47a9-9869-857390901298)

How to solve this problem? Thank you.

**Comment by dequeueing** [comment]
Plus, I have successfully imported the data.

**Comment by WhatWEat** [comment]
try to use @Servive instead of @Component

**Comment by hezean** [comment]
this may be a matter of the component scan scope. if the above solution doesn't work, you could send your code to me: heza2020@mail.sustech.edu.cn

**Comment by dequeueing** [comment]
> this may be a matter of the component scan scope. if the above solution doesn't work, you could send your code to me: [heza2020@mail.sustech.edu.cn](mailto:heza2020@mail.sustech.edu.cn)

I have tried as instructed but the problem still existed. An email has been sent to you. Thank you!

**Comment by hezean** [comment]
For anyone who encountered a similar problem, please refer to:
https://www.baeldung.com/spring-autowired-field-null

**Comment by Laihb1106205841** [comment]
I have come across a familiar problem. My solution is，add a statement in sustc.runner's gradle：
implementation 'org.springframework.boot:spring-boot-starter-jdbc'
