### ISSUE TITLE
[BenchmarkService] Will the full test code be released?

### ISSUE THREAD

**Issue by FrostyHec** [hezean/sustc#44]
### Describe your question

I noticed that only the importData functionality is tested in the benchmark currently, and I was wondering if the full test code will be released to we students to verify the correctness of the program? Thanks.

**Comment by hezean** [comment]
@Linly1080 can you push up the process?

**Comment by FrostyHec** [comment]
Sorry for bothering, I wonder if there's any news for releasing full test code? Thanks~

**Comment by hezean** [comment]
it's expected to be released tonight
~~i've been writing std program + test script + data generator for two whole days and need an urgent sleep, though that wasn't my job :(~~

**Comment by FrostyHec** [comment]
We really appreciate your hard work, thanks a lot (ˊᗜˋ)/ᵗᑋᵃᐢᵏ ᵞᵒᵘ*

**Comment by hezean** [comment]
@sses7757 will do some final checks and merge the [benchmark](https://github.com/hezean/sustc/tree/benchmark) branch to main soon.

some new data have been uploaded to http://172.18.34.154/
