### ISSUE TITLE
[Database Service] The video data of small data

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#46]
### Describe your question

The reviewer's mid of BV1Kb411L79v is 0, which is not exist in UserRecord.
Should all reviewers are in UserRecord?

**Comment by sses7757** [comment]
@Cerulime 
I downloaded the latest small data and cannot find the record you described in the small dataset. The closest one has a proper reviewer. Have you download the latest data?
![image](https://github.com/hezean/sustc/assets/27769442/d65aa39d-3d9b-4caf-8652-0b2e1d954f10)

**Comment by Cerulime** [comment]
@sses7757 
SHA1: b4b7f8a06fb0a1db30a0ed1f33687e44ea730c99
That is the data I got.

> @Cerulime I downloaded the latest small data and cannot find the record you described in the small dataset. The closest one has a proper reviewer. Have you download the latest data? ![image](https://private-user-images.githubusercontent.com/27769442/291062156-d65aa39d-3d9b-4caf-8652-0b2e1d954f10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTc0MDYsIm5iZiI6MTcwMjgxNzEwNiwicGF0aCI6Ii8yNzc2OTQ0Mi8yOTEwNjIxNTYtZDY1YWEzOWQtM2Q5Yi00Y2FmLTg2NTItMGIyZTFkOTU0ZjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDEyNDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTg1ZTYzODc3YzA1ZGI0NjNiZDMzMmZlNjFkOWUyZTM3OWM3NjljMWM2YTc4YzIyMzJmM2Y5OGRmMTBhNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dOUnPrlBwp3YGJyUuJF_1MPMzdKz7Kfa27awEITxNz4)

**Comment by sses7757** [comment]
@Cerulime
The downloaded `data.zip` has SHA1 of 6B6C7D86C315243DC139ACBC31A951C3A8A99921.

**Comment by Cerulime** [comment]
> @Cerulime The downloaded `data.zip` has SHA1 of 6B6C7D86C315243DC139ACBC31A951C3A8A99921.

@sses7757 
I refer to the videorecord.ser. Sorry.

**Comment by sses7757** [comment]
@Cerulime 
It is B4B7F8A06FB0A1DB30A0ED1F33687E44EA730C99, the same as yours.
You can print the given `VideoRecord` with BV1Kb411L79v and see its reviewer mid. Mine is 271585 rather than 0.

**Comment by Cerulime** [comment]
> @Cerulime It is B4B7F8A06FB0A1DB30A0ED1F33687E44EA730C99, the same as yours. You can print the given `VideoRecord` with BV1Kb411L79v and see its reviewer mid. Mine is 271585 rather than 0.

![屏幕截图 2023-12-17 213427](https://github.com/hezean/sustc/assets/117963019/88dd992f-e79e-45c0-9c4e-e9c7991d6d7a)
 
I don't know what happened on the data.

**Comment by sses7757** [comment]
@Cerulime 
My output is empty, meaning that I cannot find any video record with reviewer mid of 0. Maybe your problem is caused by the fury deserialization? However, I am not in charge of that part. Maybe other collaborators like @hezean or @XiaoMingZHM can resolve this issue with some additional information you provide.
