### ISSUE TITLE
[Benchmark] Invalid birthday in big data

### ISSUE THREAD

**Issue by Cerulime** [hezean/sustc#47]
### Related module

Benchmark

### What happened

The format of birthday is not "X月X日"

> ERROR 7760 --- [           main] i.s.service.impl.DatabaseServiceImpl     : Invalid birthday: 02-29

### How to reproduce

Change the data or give a clear decription of birthday.

**Comment by sses7757** [comment]
@Cerulime 
I downloaded the latest small data and cannot find the record you described in the small dataset. The result is empty. Have you download the latest data?

**Comment by Cerulime** [comment]
> @Cerulime I downloaded the latest small data and cannot find the record you described in the small dataset. The result is empty. Have you download the latest data?

Invalid in *big data*. Could you check again?

**Comment by sses7757** [comment]
@Cerulime 
Sorry about the mistake. However, I have checked on the big data again and no birthday input with `02-29` is found.
You can try print the `UserRecord` with birthday `02-29`. My output is empty.

**Comment by Cerulime** [comment]
> @Cerulime Sorry about the mistake. However, I have checked on the big data again and no birthday input with `02-29` is found. You can try print the `UserRecord` with birthday `02-29`. My output is empty.
@sses7757 
>  INFO 10700 --- [           main] i.s.service.impl.DatabaseServiceImpl     : User mid: 797719
> ERROR 10700 --- [           main] i.s.service.impl.DatabaseServiceImpl     : Invalid birthday: 02-29

**Comment by Cerulime** [comment]
> @Cerulime Sorry about the mistake. However, I have checked on the big data again and no birthday input with `02-29` is found. You can try print the `UserRecord` with birthday `02-29`. My output is empty.

Sorry, I didn't update the latest data. There is no problem about birthday.
