### ISSUE TITLE
disappeared command

### ISSUE THREAD

**Issue by freshtian** [hezean/sustc#51]
### Related module

Shell

### What happened

Throws an exception after entering a command:No command found

**Comment by freshtian** [comment]
<img width="474" alt="屏幕截图 2023-12-18 233033" src="https://github.com/hezean/sustc/assets/112839298/c7786d60-ac21-498d-9da4-c6698737788e">

**Comment by freshtian** [comment]
<img width="239" alt="屏幕截图 2023-12-18 201840" src="https://github.com/hezean/sustc/assets/112839298/9aeb6e5f-afd8-4edf-95a5-a93847458d73">

**Comment by hezean** [comment]
have you implemented DanmuService and mark your implementation as `@Service`?
