### ISSUE TITLE
About RecommenderService impl recommendVideosForUser method

### ISSUE THREAD

**Issue by Yao1OoO** [hezean/sustc#52]
### Describe your question

请问一下RecommenderService这个接口第三个方法recommendVideosForUser描述中提到If the current user's interest is empty, return {@link io.sustc.service.RecommenderService#generalRecommendations(int, int)}.
     * If the requested page is empty, return an empty list
还提到{@code pageSize} and/or {@code pageNum} is invalid (any of them <= 0)
请问这个requested page为空包含什么呢？感觉如果page等于0就被第三种情况包含了，查询结果为空被第一种情况包含了

这个接口中方法要求提供的pageSize和pageNum具体是什么意思？是要求提供多少页还是要求提供第几页？

**Comment by sses7757** [comment]
@Yao1OoO 
1. pageSize是每一页的大小，pageNum是我们希望拿到这样分页下的第几页（从第1页开始）
2. "If the requested page is empty, return an empty list"意思是如果给定的pageSize下希望拿到的pageNum超过了实际最大页数（比如pageSize=50时一共4页，但是pageNum=5），则返回空列表
