### ISSUE TITLE
[bootRun RecommenderCommand] 

### ISSUE THREAD

**Issue by Bulu04bulu** [hezean/sustc#53]
### Related module

Shell

### What happened

When I use the 'rec general' command and enter invalid pagenum and pagesize(like -1 -1), it will automatically take the default value(1 10), then how to test my API implementation of corner case. If my input is valid, it will take it as the correct input.

**Comment by Bulu04bulu** [comment]
![QQ图片20231219100053](https://github.com/hezean/sustc/assets/104877638/460d6a6d-ce7a-48cd-a3b7-02cb56aff496)
![QQ图片20231219100048](https://github.com/hezean/sustc/assets/104877638/8539be45-0a7c-41c4-b131-cba7a32c8db2)

like that, I print out the parameter.

**Comment by hezean** [comment]
that's a bug of spring shell (https://github.com/spring-projects/spring-shell/issues/651), and was fixed in release 3.1.x

however, since our project wants to be compatible with java 8, we cannot upgrade these dependencies. instead, you may use named options to bypass the bug:

```
rec general --pageSize -1 --pageNum -2
```
