### ISSUE TITLE
[VideoService] What is the return of getHotPot()?

### ISSUE THREAD

**Issue by maxinglo** [hezean/sustc#56]
### Describe your question

The definition of 'Hotpot' in the comments refers to the interval with the 'most' Danmu, but the return value is a set containing the index or indices of hotpot's'. Could you clarify whether it is one or multiple?

**Comment by sses7757** [comment]
@maxinglo 
There may be one or multiple hotspots in a video with equal amount of danmus. Hence, a set shall be returned.
