### ISSUE TITLE
[VideoService] how to calculate these cases in searchVideo

### ISSUE THREAD

**Issue by redhecker** [hezean/sustc#58]
### Describe your question

as i do not have a good understand of the discription in searchVideo, i wonder what is the relevance of the following cases:

kewords: "java  data  ava"

case 1:  title "javajava", owner "a", discription "b"
case 2:  title "java  javadata", owner "a", discription "database"

**Comment by WhatWEat** [comment]
case 1: 
  - title includes 2 "java" and 2 "ava"
 
  so the relevance is **4**

 case 2:
  - title includes 2 "java", 2 "ava" and 1 "data"
  - des includes 1 "data"
  
  so the relevance is **6**

**Comment by dequeueing** [comment]
> case 1:
> 
> * title includes 2 "java" and 2 "ava"
> 
> so the relevance is **4**
> 
> case 2:
> 
> * title includes 2 "java", 2 "ava" and 1 "data"
> * des includes 1 "data"
> 
> so the relevance is **6**

```
A character in these fields can only be counted once for each keyword but can be counted for different keywords.
Examples:
If the title is "111" and the keyword is "11", then the relevance in the title is 1 (one for the occurrence of "11").
```
Hello, reviewer. Could you again explain the upper example extracted from `searchVideo`. Why the relevance is 1, instead of 2 because "111" includes two "11"?

Thank you.

**Comment by redhecker** [comment]
> > case 1:
> > 
> > * title includes 2 "java" and 2 "ava"
> > 
> > so the relevance is **4**
> > case 2:
> > 
> > * title includes 2 "java", 2 "ava" and 1 "data"
> > * des includes 1 "data"
> > 
> > so the relevance is **6**
> 
> ```
> A character in these fields can only be counted once for each keyword but can be counted for different keywords.
> Examples:
> If the title is "111" and the keyword is "11", then the relevance in the title is 1 (one for the occurrence of "11").
> ```
> 
> Hello, reviewer. Could you again explain the upper example extracted from `searchVideo`. Why the relevance is 1, instead of 2 because "111" includes two "11"?
> 
> Thank you.

i think that is because in the description of the interface, it says that "A character in these fields can only be counted once for each keyword but can be counted for different keywords.", thus there is only one "11" in "111"

**Comment by WhatWEat** [comment]
redhecker's explanation is right.
