### ISSUE TITLE
How to get search results from command line?

### ISSUE THREAD

**Issue by lxy-quantum** [hezean/sustc#61]
### Describe your question

How can we get search results of videos from command line?

**Comment by WhatWEat** [comment]
In ```sustc-runner/src/main/java/io/sustc/command/VideoCommand.java```, you can find a method name **searchVideo** listing all the parameters you can input.

Here is an example:
```
video search --mid 1 --pwd 1 --pageSize 10 --pageNum 1
```
If the command line indicates that this command does not exist, you can refer to this for a solution #51 .
