### ISSUE TITLE
如何传入空值

### ISSUE THREAD

**Issue by Illustrious19** [hezean/sustc#62]
例如user register 中
我想把birthday设置为空
应该如何输入指令，是在birthday的位置输入“null”还是输入什么其他的

**Comment by sses7757** [comment]
@Illustrious19 
Simply use command `user register` without providing the birthday command line parameter.

**Comment by Illustrious19** [comment]
能给一个具体的例子吗，谢谢。

**Comment by hezean** [comment]
```
user register --name "..." --password "..."
```

find the arguments here
https://github.com/hezean/sustc/blob/main/sustc-runner/src/main/java/io/sustc/command/UserCommand.java
