### ISSUE TITLE
Another way to implement service?

### ISSUE THREAD

**Issue by dequeueing** [hezean/sustc#63]
### Describe your question

Hello reviewer. 

- Since we execute sql statements via JDBC, is it feasible that we preliminarily create views when we create tables (in that sql file), and then directly select infomation from the view using JDBC?
- If it is viable, what would be the potential cost of it, especially when testing the performance of database?

Many thanks!

**Comment by hezean** [comment]
- that's allowed
- it may make your program faster or not, you should do some benchmark by your self, like writing a benchmark step in the benchmark service to call an api
