### ISSUE TITLE
[Shell] After 11 commands of rec general, the connection becomes not available.

### ISSUE THREAD

**Issue by Ray0v0** [hezean/sustc#66]
### Related module

Shell

### What happened

<img width="880" alt="image" src="https://github.com/hezean/sustc/assets/106433276/3ee4e599-ab09-48ea-8fcb-8cdd8ca1b4ef">
The function acts normally before the 11th epoch. But at the 11th epoch (or maybe after a specific time), the connection becomes not available.

**Comment by hezean** [comment]
did you properly close the connection? the connection pool holds 10 connections and if you didn't close the connection after using it, later requests cannot acquire one.

**Comment by sses7757** [comment]
@Ray0v0 
I have tried executing 10 `rec general` with correctly implemented program, no similar error was thrown.
As mentioned by @hezean, usually these kind of errors are caused when you forget to release the connection or similar resources at the end of **each** of your implemented API calls.

**Comment by mmhct** [comment]
![image](https://github.com/hezean/sustc/assets/150405597/9a739caf-b2a7-4a83-b5c0-66c61e3827b5)
Does database connections automatically release? Here I tried to write conn.close() but IDE tells me it is redundent.

**Comment by sses7757** [comment]
@mmhct 
When using `try (... conn ...) { ... }`, the connection will be released automatically. This issue may relate to the framework used, you may continue the discussion in #83 together with other students who have similar problems.
