### ISSUE TITLE
Database connect failed

### ISSUE THREAD

**Issue by Moxin12212810** [hezean/sustc#67]
### Describe your question

I have created a common account and I've given it access to the database. And I also test it, it works in datagrip. But in idea, bootrun and benchmark both report this error when I was trying to test my code like "db import" or just "db sum 1 2".
![UGEU1$ $_NY6W42J0%Y~LYQ](https://github.com/hezean/sustc/assets/119912023/4e5a9c1b-0782-4d0c-bbf8-fa1299f46619)
![51Y}5LWP%768(1}XE 850CF](https://github.com/hezean/sustc/assets/119912023/f66fc619-a34f-4bb1-a3e6-b0142b72d268)

I have updated all code about UTF-8 and I guarantee the information in application.yml is correct.

**Comment by WhatWEat** [comment]
**Try logging in with a non-postgres account.**

**Comment by Moxin12212810** [comment]
What is a non-postgres account mean? Is that mean a account which is not a super account? But what I used in the picture is not a super account. You can see the Username is wyf, a common account.

**Comment by sses7757** [comment]
@Moxin12212810 
Since your error message is not properly decoded, I tried creating a non-superuser and have error of `permission denied`. My error is caused by the table truncation commands. Generally, since all the tables shall be removed at the beginning of the benchmark, you are required to provide a user with enough privileges, and that user must be able to login.

**Comment by Moxin12212810** [comment]
@sses7757 
I have given these permissions to `wyf` accounts using `postgres `accounts：
```
grant connect on database sustc to wyf;
grant usage on schema public to wyf;
grant select, insert, update, delete, truncate on all tables in schema public to wyf;

```
Aren't these enough?

**Comment by sses7757** [comment]
@Moxin12212810 
What is your role creation statement? Did you create your role with `LOGIN`?

**Comment by Moxin12212810** [comment]
@sses7757  
When I was creating `wyf` account and giving it those permissions, the `postgres `account is logged in. And after that I also logged `wyf` account to test its permissions. There's no wrong and the permissions can work.

**Comment by Moxin12212810** [comment]
@sses7757 
Sorry, there's something wrong. I can't insert value into the table. But why this would happen? I'm sure that I gave the insert permission to `wyf `account by the superuser `postgres`
![8OH30X(OS{MSGBF8YX%NGHM](https://github.com/hezean/sustc/assets/119912023/6248f12c-0fe6-44cb-9f82-fdfbf6675fb7)

**Comment by sses7757** [comment]
@Moxin12212810 
You can try removing and recreating your user. If that still does not work, I think that you may consult TA or SA at lab class for help.

**Comment by Moxin12212810** [comment]
@sses7757 
I have found the source of this error. Because I use serial id in some tables, so those table need a `seq` permission. I give the non-superuser this permission and it can insert now. But in idea, I still have the same problem. I just execute `db sum 1 2` and it reports the same error. In all, I don't think it's the permissions, it's the fact that I'm not connected to the 
![P A@YTX)HWV$W`EK67@UYVY](https://github.com/hezean/sustc/assets/119912023/dfcff85c-76c1-4d74-8997-f0b117dcfb54)
database.

**Comment by sses7757** [comment]
@Moxin12212810 
Is this problem solved? If not, please change to correct encoding and print the full satcktrace.

**Comment by Moxin12212810** [comment]
This problem is not solved, but I meet new problem now and I can even not build gradle now. I'm nearly crazy now.


![}@)%3RE3)C6D_TG4M B{` A](https://github.com/hezean/sustc/assets/119912023/4e16ca1a-53c3-4988-85f1-5f724b6da719)

I can not debug my code and it is the worst thing in project. And my ddl is this Thursday. I'm helpless now.
