### ISSUE TITLE
[Shell] Modifications not updated

### ISSUE THREAD

**Issue by dequeueing** [hezean/sustc#68]
### Related module

Shell

### What happened

I found that my modifications won't be updated. For example: I change somewhere in `public Integer sum(int a, int b) {` like this: 

![image](https://github.com/hezean/sustc/assets/127177415/140e851b-dfa5-434a-badd-f01d494d8a7e)

Then I run bootRun. Amazingly, it still comes the correct result.

![image](https://github.com/hezean/sustc/assets/127177415/2a09c1f7-6de9-4cd9-ba02-33b8d1bdf48d)

What I have tried: restart bootRun, restart IDE, restart computer, truncate the tables and import them again. All fail.

I am really really confused. How to solve this?

Thank you!

**Comment by hezean** [comment]
did you generate a jar?

https://github.com/hezean/sustc/blob/2a596f950bb6b2132eb4f35347a3e61ebd14f168/README.md?plain=1#L147-L148

**Comment by dequeueing** [comment]
Problem solved.  Thank you.
