### ISSUE TITLE
[BenchMark] EmptySet Not Found Exception

### ISSUE THREAD

**Issue by Cypher-Bruce** [hezean/sustc#69]
### Describe your question

I try to benchmark my code with `large-data` in the latest data.zip (SHA-256: f31494e7b76f72961f78983bb505e33e4446d80da4e78520481c5202b6de946c) but it always fails at `Step 4: Test VideoService#getHotspot(String)`. 

Here is the error message:
![image](https://github.com/hezean/sustc/assets/53269096/eaa6699f-50a7-4bfa-8c2f-882db8e66dff)

I've updated my Kotlin plugin in IntelliJ IDEA to 233.13135.103-IJ (which seems to be the latest version in IDEA). And this `getHotspot` function do work when I run it with `bootRun`. I return a `Collections.emptySet()` on corner case.

How can I fix this?

**Comment by hezean** [comment]
sorry, do you mean you are using kotlin? actually my std program was written in kotlin and it may be an issue on the test case generator

**Comment by Cypher-Bruce** [comment]
No, I'm not using Kotlin. I just update the plugin to make sure it's not the plugin's problem.

Here is a full error message:

![image](https://github.com/hezean/sustc/assets/53269096/36a33061-9e65-4acb-9cbc-67afa4c4dae3)

![image](https://github.com/hezean/sustc/assets/53269096/d86bdfb6-be8d-4785-b93a-c3f3ca500cb2)

**Comment by JianuoZhu** [comment]
Encountered the same problem

**Comment by hezean** [comment]
sorry for the inconvenience, it was fixed in https://github.com/hezean/sustc/commit/695a506913a75040bd9106efb10efacf6fe91676, please update to the latest code 🙏
