### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by SRKWChidori** [hezean/sustc#72]
### Describe your question

I have already put the files into required document, but it can't find them when I import.

**Comment by sses7757** [comment]
@SRKWChidori 
Please provide more information about your problem, such as the exact location of your `.ser` files and the error messages.

**Comment by SRKWChidori** [comment]
Here is my path of .ser files.
"……\sustc-main\sustc-runner\data\import\ .ser"

**Comment by SRKWChidori** [comment]
> Here is my path of .ser files. "……\sustc-main\sustc-runner\data\import\ .ser"

**Comment by SRKWChidori** [comment]
> @SRKWChidori Please provide more information about your problem, such as the exact location of your `.ser` files and the error messages.
Here is my path of .ser files.
"……\sustc-main\sustc-runner\data\import\ .ser"

**Comment by sses7757** [comment]
@SRKWChidori 
What is the full error message?

**Comment by SRKWChidori** [comment]
> @SRKWChidori What is the full error message?

Thank you for reply. I have solved this problem now.
