### ISSUE TITLE
How to avoid data import multiple times?

### ISSUE THREAD

**Issue by Flitieter** [hezean/sustc#73]
### Describe your question

Every time I run the benchmark, I notice the data import runs again, which costs me a lot of time. So is there a way to avoid this case?

**Comment by WhatWEat** [comment]
## Step 1: Using PostgreSQL's COPY Feature

1. PostgreSQL provides a `COPY` functionality that can be used to back up data from the `public` schema to another schema.
2. This operation can be performed visually in DataGrip.
    - Right-click on the schema and select the `Import/Export` option.
    - Here, you will find the option `copy table to...`.
    - Alternatively, you can select the schema and press `F5` as a shortcut.

## Step 2: Modifying `benchservice.java`

1. In the `benchservice.java` file, comment out the steps involving `truncate` and `db import` for `order = 0` and `order = 1`.
2. After completing the above steps, every time you modify data in the `public` schema, you can drop it and then repeat the process to copy a backed-up version.

### Important Note:
- Be aware that the `COPY` operation might not preserve the sequence of your series or any defined functions.
