### ISSUE TITLE
[Benchmark] Could you provide a demo?

### ISSUE THREAD

**Issue by dequeueing** [hezean/sustc#74]
### Describe your question

Hello reviewer. I am wondering are there any explanations on Benchmark? I think the description in README is not enough. Would it be possible for you to provide a demo related to it?

Thanks.

**Comment by WhatWEat** [comment]
unzip the small_data.zip and put directories named **import** and **test** into **data** directory.
Just like this:
```
data # Under the runner
├── import      # include 3 ser files
└── test   # include many ser files
```
