### ISSUE TITLE
Why all method have the NullPointerException problem?

### ISSUE THREAD

**Issue by sketchplane23** [hezean/sustc#76]
When I run benchmark on my computer, every method can't run and return nullpointerexception like this. I'm really puzzled about this problem. What may cause this?

![1](https://github.com/hezean/sustc/assets/131460680/7d360f8e-6b4a-4e9f-832a-c6f450f9fcb5)
![2](https://github.com/hezean/sustc/assets/131460680/ea088b0a-043b-497d-8884-dbad8f45b10d)

**Comment by sketchplane23** [comment]
every check contains this problem...nullpointerexception
![图片](https://github.com/hezean/sustc/assets/131460680/ac40cb6c-b536-47cd-b2b4-6276af745b7f)
![图片](https://github.com/hezean/sustc/assets/131460680/bca79918-1494-4c20-ac80-73c51313be8c)
![图片](https://github.com/hezean/sustc/assets/131460680/d125d0fc-270c-4e65-af64-606ee796848f)

**Comment by hezean** [comment]
have you marked your implementation with `@Service`? did you succeed to run the program in the interactive cli mode?
