### ISSUE TITLE
[Register] Unknown register errors

### ISSUE THREAD

**Issue by Gin5567** [hezean/sustc#78]
### Describe your question

register
Wrong answer for RegisterUserReq(password=8db5e609749c4957, qq=998970494167868265018424, wechat=null, name=aaaafde0c, sex=FEMALE, birthday=7月30日, sign=7ccf8514-a89a-45): expected < 0, got 3546378525477864

Why is this invalid? 

birthday format is correct
have name,password,sex
no same qq in the database

**Comment by WhatWEat** [comment]
You are right. That's my problem
