### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by GanLiuuuu** [hezean/sustc#79]
### Related module

Database

### What happened

i downloaded and tested https://github.com/hezean/sustc/commit/695a506913a75040bd9106efb10efacf6fe91676. It failed to connect the database. But this problem didn't occur with the previous versions.
<img width="1305" alt="Screenshot 2023-12-25 at 16 18 02" src="https://github.com/hezean/sustc/assets/119108256/7a97dd99-1ef0-4ac5-8214-9cb7fed309cf">

**Comment by hezean** [comment]
是网络有问题 在下载依赖时炸了，跟数据库没关系
换个网重试一下就行
