### ISSUE TITLE
Unable to add the org.springframework.stereotype library

### ISSUE THREAD

**Issue by Fay20050308** [hezean/sustc#82]
After updating the code recently modified by the teaching assistant, I encountered an issue where the Service cannot be resolved. The error disappears when I click 'add,' but reappears after refreshing Gradle. Additionally, there is no progress bar during the 'add' operation. How can I resolve this issue?
![屏幕截图 2023-12-25 221809](https://github.com/hezean/sustc/assets/133669516/e9eab5d1-ecd4-4d40-a4b4-291e3e7f2cf0)
![Uploading 屏幕截图 2023-12-25 221931.png…]()

**Comment by hezean** [comment]
can you run the program using the command line with:
```shell
./gradlew bootRun
```

and provide the output? i think that maybe the problem of ide

**Comment by hezean** [comment]
<img width="362" alt="Screenshot 2023-12-25 at 22 41 22" src="https://github.com/hezean/sustc/assets/49837965/29a5f02b-04bb-4df5-9eaf-9a73354a896a">

or try invalidate all caches.

**Comment by Fay20050308** [comment]
I resolved the issue by clearing the cache. Thank you！

**Comment by Fay20050308** [comment]
But now I am facing a new issue.
![屏幕截图 2023-12-25 232719](https://github.com/hezean/sustc/assets/133669516/6a9eadb8-71d3-44a3-af43-ae137291811d)

**Comment by Fay20050308** [comment]
I can't add this library either now
![Uploading 屏幕截图 2023-12-26 000117.png…]()
.

**Comment by sses7757** [comment]
@Fay20050308 
I cannot see your uploaded image, maybe you can try to edit your comment to upload it again.

**Comment by hezean** [comment]
@Fay20050308 did you solve the problem? we hardly can provide any help without more info. i'd close this issue since it's considered stale with no update in 4 days, please feel free to re-open it if you're back
