### ISSUE TITLE
Benchmark can not run

### ISSUE THREAD

**Issue by V1Zhang** [hezean/sustc#84]
### Related module

Code in sustc-api

### What happened

With the same code as my group member, I can't run benchmark but they can. Maybe there is something wrong with application when running in my environment. One SA told me many people meet that problem so how to solve it
<img width="784" alt="benchmark" src="https://github.com/hezean/sustc/assets/132585868/411f40b3-158d-4874-927e-b7fa27c3764d">

**Comment by WhatWEat** [comment]
I understand that you're anxious, but in order to consolidate the reasons for the framework error and make it easier for others to review later, could you please move to #83 and post again, including **all the error messages**?

Thanks
