### ISSUE TITLE
[BenchMark] Number of Test Case Dismatch

### ISSUE THREAD

**Issue by Cypher-Bruce** [hezean/sustc#86]
### Describe your question

When benchmarking online or locally for step 19 `Test VideoService#reviewVideo(AuthInfo, String)`, my passcnt is 3. There is only 1 wrong answer debug info in the console. So the actual number of test case is 4? However, both the `benchmark_small.json` and OJ tell me number of test case is 35.

I try to add this code at the beginning of  my `reviewVideo` function:
```
debug ++;
log.debug("VideoServiceImpl::reviewVideo: debug {}", debug);
```
where `debug` is a static variable for the impl class outside any function.

And the output in the console confirms there are only 4 test cases:
![image](https://github.com/hezean/sustc/assets/53269096/57a8ee19-510d-465f-b329-e6261ecf46da)

**Comment by hezean** [comment]
![image](https://github.com/hezean/sustc/assets/49837965/56e1ab98-006a-4adc-b687-216db9b5da0d)

除了ser里的几个测试点，我们还测了review之前post的视频，这部分测试是并发的，你的debug变量如果是普通的int/long会没办法正确统计，因为race condition了，需要用atomic int来统计，参考benchmark service的写法

**Comment by Cypher-Bruce** [comment]
Thank you for your reply.
