### ISSUE TITLE
Can't get "Likedby" in DanmuRecord

### ISSUE THREAD

**Issue by sketchplane23** [hezean/sustc#87]
When I try to import data into "like Danmu" table, I need to use the "Likedby" attribute in "DanmuRecord". But while using "getLikedby()" method, It always give back a null value. What may cause this?

**Comment by sses7757** [comment]
@sketchplane23 
Can you provide more information including error messages and your related codes?

**Comment by sketchplane23** [comment]
![图片](https://github.com/hezean/sustc/assets/131460680/3b8e8e1f-c574-42b4-98b5-f68321bb648f)
for example,when I try to get  and print   "likedby",there is a null

**Comment by sses7757** [comment]
@sketchplane23 
What is this danmu? Can you `System.out.println(danmu)` and show the result? Since there is no null `likeBy` in the given data.
Besides, have you confirmed the correctness of your downloaded `.ser` data file? Is this problem reproduceable in other computers?

**Comment by yzh0811** [comment]
Yes,this problem also happened in my computer,if we use System.out.println(danmu),it will print "DanmuRecord{likedBy=null}",we have determined that our .ser data file is the same with the sa in this morning.

**Comment by sses7757** [comment]
@yzh0811 @sketchplane23 
Although I cannot reproduce the bug, some SA also noticed that the printed objects may be null in asynchronous operations. However, they can execute their codes and successfully import data. You can check the database to see whether the import process is successful.

**Comment by yzh0811** [comment]
You mean we need to import the likeby no matter whether it is null or not?Because it may succeed?

**Comment by hezean** [comment]
you may try replacing all `cases.xxx.parallelStream().forEach` to `cases.xxx.forEach` (remove the parallel stream) to overcome the log-null issue for better bugging.
