### ISSUE TITLE
[BenchmarkService] class cast exception in step 9

### ISSUE THREAD

**Issue by GanLiuuuu** [hezean/sustc#91]
### Describe your question

I'm testing my code with [85d216f](https://github.com/hezean/sustc/commit/85d216fbb1cb7ca92549914cc6dd8e0b78c5b12a). There are error messages like these
<img width="1458" alt="Screenshot 2023-12-26 at 16 19 57" src="https://github.com/hezean/sustc/assets/119108256/b07fbab7-2a48-4d0b-b5ea-0b1f72aacf7c">

**Comment by hezean** [comment]
Please update ur data

**Comment by GanLiuuuu** [comment]
> Please update ur data

thank u! the problem is fixed now
