### ISSUE TITLE
[Benchmark] How to set the log level?

### ISSUE THREAD

**Issue by dequeueing** [hezean/sustc#93]
### Describe your question

Hi. I 've been using log to help me with debug. But in Benchmark there are too many records and I just want to see the _debug_ level ones. How to configure it ?

![image](https://github.com/hezean/sustc/assets/127177415/205ea4a4-75fe-47f4-81d5-454342e18130)

I tried to modify the application.yml file but it didn't work because I don't actually know how it works.

Thank you.

**Comment by hezean** [comment]
If you want the debug level to be displayed, the info level will also be displayed. Alternatively, you can change the debug level to higher ones, like warn or error, and modify the application.yml file

![image](https://github.com/hezean/sustc/assets/49837965/a32dc91e-f0a1-4357-a557-f0c8a934433e)
