### ISSUE TITLE
[DanmuService: danmulike ] java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by SRKWChidori** [hezean/sustc#94]
### Related module

Code in sustc-api

### What happened

When I run benchmark step 12, this error happen. And its error location come from testbench.

**Comment by hezean** [comment]
that could be caused by your error responses in step 10, and throwing the exception won't affect our evaluation of your program's correctness. moreover, as we intentionally overlook the performance of step 12, this won't have any other affection

**Comment by SRKWChidori** [comment]
> that could be caused by your error responses in step 10, and throwing the exception won't affect our evaluation of your program's correctness. moreover, as we intentionally overlook the performance of step 12, this won't have any other effect

So I could ignore the passCnt of step 12 ?

**Comment by hezean** [comment]
you should try correcting your `sendDanmu` (step 10) before further working on step 12
