### ISSUE TITLE
Fail to disable the triggers.

### ISSUE THREAD

**Issue by Ray0v0** [hezean/sustc#96]
### Describe your question

In #89, you said the commands like "ALTER TABLE users DISABLE TRIGGER ALL;" is able to run. However, the benchmark throws Exception like this. Does there has any ways to run this command correctly, or it is just banned?
<img width="1108" alt="9c3b120aad1098ac76907e449199af9e" src="https://github.com/hezean/sustc/assets/106433276/013df2f8-6a43-4357-b7e7-474bd08ea2fc">

**Comment by WhatWEat** [comment]
似乎是因为你disable了一个system trigger，我们只给予你db的owner，你无法对系统进行更改，你可以尝试插入结束添加trigger，或者一个一个diable你的trigger，又或是不disable触发器，毕竟满分仅需要用批处理和手动commit
