### ISSUE TITLE
About user‘s following

### ISSUE THREAD

**Issue by alkane7** [hezean/sustc#98]
### Describe your question

导入的数据中包括user follow自己的情况，这种情况是合法的吗？需要在导入数据的时候删除这种数据吗？[
![image](https://github.com/hezean/sustc/assets/133130114/eb55d94c-11ae-421e-949e-a99b8e17587b)
](url)

**Comment by WhatWEat** [comment]
不用删除，但记得api里如果自己follow自己，记得return false
