### ISSUE TITLE
[Import Data] Questions abt video data

### ISSUE THREAD

**Issue by GanLiuuuu** [hezean/sustc#99]
请问在import data中，视频数据包括bv=‘BV1vZ4y187Zs’的视频吗？ Benchmark中的generalRecommendation中有expected这条视频。
![Screenshot 2023-12-27 at 12 55 45](https://github.com/hezean/sustc/assets/119108256/644d72fd-02fe-4bf3-88e6-6a9e2cdd4345)

但当我在数据库中搜索时，没有搜索到这条视频。麻烦啦。
<img width="402" alt="Screenshot 2023-12-27 at 12 56 31" src="https://github.com/hezean/sustc/assets/119108256/263598fd-e2b1-4524-af52-b3f500374da6">

**Comment by hezean** [comment]
![292962558-644d72fd-02fe-4bf3-88e6-6a9e2cdd4345](https://github.com/hezean/sustc/assets/49837965/a630a71d-b634-46c0-a07a-ca6a10f2d393)

这个视频是存在的，从你其他查询中可以看到它

你手动查询时查不到可能是后续的测试步骤删除了这个视频，请在cli中执行 db import 重新导入干净数据，另外请检查ide连接的database与程序配置的是否是同一个

**Comment by GanLiuuuu** [comment]
> ![292962558-644d72fd-02fe-4bf3-88e6-6a9e2cdd4345](https://private-user-images.githubusercontent.com/49837965/293026499-a630a71d-b634-46c0-a07a-ca6a10f2d393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODQ0ODIsIm5iZiI6MTcwMzY4NDE4MiwicGF0aCI6Ii80OTgzNzk2NS8yOTMwMjY0OTktYTYzMGE3MWQtYjYzNC00NmMwLWEwN2EtY2E2YTEwZjJkMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDEzMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjMzMTcxYjZhNzg3YTA4ODJmYzZkZjVhMDgxZTQ3ZTM0Njk5ODE0ZjgwMGZkOTVjMDE0M2RhMDkwNjM0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c4y1y-yWiTsBQjDH1JPa3kAkjpn_3hYqJkORbkbaCZI)
> 
> 这个视频是存在的，从你其他查询中可以看到它
> 
> 你手动查询时查不到可能是后续的测试步骤删除了这个视频，请在cli中执行 db import 重新导入干净数据，另外请检查ide连接的database与程序配置的是否是同一个

ok thx!
